In [2]:
import numpy as np

an array is initialised as numpy.array(object)<br>
The dtype of np arrays is ndarray <br>
The  dtype precedence is str > float  >int. The dtype of all vals get converted to that of the val with highest precedence <br>
## Creating an array
numpy.array(object,dtype = None,copy = True,order = None,subok= False,ndim=0) <br>
ex - **x = np.array([1,2,3], dtype = float, ndim = 2)**

## Creating an empty array
np.empty(shape, dtype = ?)<br>
ex- **x = np.empty([3,2], dtype = int)**

## Creating an arry of zeros or ones
np.zeros(shape, dtype = ?)<br>
np.ones(shape, dtype = ?)<br>
ex - **x = np.zeros([2,3], stype = float)**

## Creating arrays from existing arrays
np.asarray(a, dtype = ?) -> a is the object/array/tuple to which the ndarray is to be initialised<br>

In [48]:
arr1 = np.array([1,2,3.,])
arr2 = np.array([ [1,2,6] , [3,4,5] ])
arr3 = np.array([1,2,3],ndmin = 2)
arr4 = np.array(1)
arr5 = np.array([[arr1,arr1],arr2])
arr = [arr1,arr2,arr3,arr4,arr5]
for i in range(5):
    print(arr[i],'\tdtype-',arr[i].dtype,'\tdim -',arr[i].ndim,'\tshape-',arr[i].shape,'\n')

[1. 2. 3.] 	dtype- float64 	dim - 1 	shape- (3,) 

[[1 2 6]
 [3 4 5]] 	dtype- int32 	dim - 2 	shape- (2, 3) 

[[1 2 3]] 	dtype- int32 	dim - 2 	shape- (1, 3) 

1 	dtype- int32 	dim - 0 	shape- () 

[[[1. 2. 3.]
  [1. 2. 3.]]

 [[1. 2. 6.]
  [3. 4. 5.]]] 	dtype- float64 	dim - 3 	shape- (2, 2, 3) 



# Numerical ranges
np.arange(start,stop,step,dtype = ?)<br>
**arange() excepts float argument for step**<br>
eg - **x= np.arange(0,5,1,float)**<br>
    x = [0. ,1. ,2. ,3. ,4.]

In [51]:
x= np.arange(0,5,1,dtype = float)
print(x)

[0. 1. 2. 3. 4.]


# Some array parameters
arr.ndim -> returns dimension of array. <br>
arr.dtype ->returns dtype<br>
arr.shape -> return a tuple of dimensions<br>
arr.reshape(r,c) -> changes shape to (r,c)

In [40]:
print(arr[1].mean())
arr[1].reshape(6,1)

3.5


array([[1],
       [2],
       [6],
       [3],
       [4],
       [5]])

# Array slicing and indexing
same as usual arrays<br>
eg - 

In [45]:
x = np.arange(10)
print(x)
print(x[::x[2]])

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


# Vectorisation 
is the process of performing the same operation in the same way for each element in an array.

# Broadcasting
- Treatment of arrays of different shape during arithmetic operations.
- Usual arithmetic operations are arried out between corresponding elements of two different arrays of sam shape.<br>

2 arrays are broadcastable if:
- They are both of the same type
- Arrays have same number of dimensions,  length of each dimension is either a common length or 1
- If the dimensions are not the same then the array obtained by prepending the shape by 1 must satisfy the above property.

In [56]:
x = np.array([3,1,2,5])
y = x[::-1]
print(5*x,'\n')
print(y*x,'\n')

x = np.array([[1,2,3,4],[4,5,6,7]])
y = np.arange(1,5)
print(x*y,'\n')

[15  5 10 25] 

[15  2  2 15] 

[[ 1  4  9 16]
 [ 4 10 18 28]] 



# Arithmetic operations
All operations are caried out element wise

In [67]:
x = np.arange(5)
y = np.arange(5,10)
print('x = ',x)
print('x - y = ',x-y)
print('x*y =',x*y)
print('x/y = ',x/y)
print('y//x = ',y//x)
print('x**2 = ',x**2)
print('x**y = ',x**y)
print('x<2 = ',x<2)
print('x<y = ',x<y)
print('x+1 = ',x+1)

x =  [0 1 2 3 4]
x - y =  [-5 -5 -5 -5 -5]
x*y = [ 0  6 14 24 36]
x/y =  [0.         0.16666667 0.28571429 0.375      0.44444444]
y//x =  [0 6 3 2 2]
x**2 =  [ 0  1  4  9 16]
x**y =  [     0      1    128   6561 262144]
x<2 =  [ True  True False False False]
x<y =  [ True  True  True  True  True]
x+1 =  [1 2 3 4 5]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


<ipython-input-67-69e9cd2ade2a>:7: RuntimeWarning: divide by zero encountered in floor_divide
  print('y//x = ',y//x)


# Matrix product:
Matrix product can be found by A@B or A.dot(B)
# Matrix transpose
A.T gives transpose of matrix A

In [65]:
A = np.array([[1,1]
            ,[0,1]])
B = np.array([[2,3]
             ,[4,5]])

print(A*B)
print(A@B)
print( A.dot(B) )
print()
print(A.T)
print(B.T)

[[2 3]
 [0 5]]
[[6 8]
 [4 5]]
[[6 8]
 [4 5]]

[[1 0]
 [1 1]]
[[2 4]
 [3 5]]


# Some operations
arr.mean() -> returns mean value <br>
arr.sum() ->sum of elements of array <br>
arr.min() <br>
arr.max() <br>
np.sin(x) -> returns array with sin(x) as terms <br>
np.sqrt(x)<br> 
np.exp(x)

In [80]:
x = np.arange(10)
print(x)
print(x.mean())
print(x.min())
print(x.var())

[0 1 2 3 4 5 6 7 8 9]
4.5
0
8.25


In [93]:
x = np.arange(2*3*2).reshape(2,3,2)
print(x)
y = np.array([[1,2,3]
             ,[0,1,2]])
print('\n', x@y )
print('\n',x.T)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

 [[[ 0  1  2]
  [ 2  7 12]
  [ 4 13 22]]

 [[ 6 19 32]
  [ 8 25 42]
  [10 31 52]]]

 [[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]


# Reshaping arrays:
The following commands return an array with modified shape.
- arr.ravel() returns a vector
- arr.reshape() chages shape according to parameters **Where -1 is used as parameter, the parameter is evaluateed by the program**
- arr.T transpose
- arr.swapaxes(axis_1,axis_2)

In [102]:
x = np.array([[[1,2,3,1]
             ,[3,0,3,2]
             ,[1,1,1,3]],
             [[1,0,1,3]
             ,[4,5,6,2]
             ,[0,0,0,1]]])
print(x.shape)
print(x)
print('\n',x.swapaxes(0,1))
print('\n',x.swapaxes(1,2))
print('\n',x.swapaxes(0,2))

(2, 3, 4)
[[[1 2 3 1]
  [3 0 3 2]
  [1 1 1 3]]

 [[1 0 1 3]
  [4 5 6 2]
  [0 0 0 1]]]

 [[[1 2 3 1]
  [1 0 1 3]]

 [[3 0 3 2]
  [4 5 6 2]]

 [[1 1 1 3]
  [0 0 0 1]]]

 [[[1 3 1]
  [2 0 1]
  [3 3 1]
  [1 2 3]]

 [[1 4 0]
  [0 5 0]
  [1 6 0]
  [3 2 1]]]

 [[[1 1]
  [3 4]
  [1 0]]

 [[2 0]
  [0 5]
  [1 0]]

 [[3 1]
  [3 6]
  [1 0]]

 [[1 3]
  [2 2]
  [3 1]]]


# Linear algebra
np.linalg contains alot of lin algebra methods,etc.<br>
- arr.eye(n) retuns nth order **identity matrix**
- arr.transpose() returns **transpose** of matrix arr
- arr.linalg.inv() returns **inverse** of matrix arr
- np.trace(arr) returns **trace** of arr 
- A @ B returns **matrix product** of two 'compatible' matrices
- np.linalg.solve(a,y) returns **sloution for linear system ax = y**
- np.linalg.eig(a) returns a tuple of complex **eigenvalues**